site_name: Car API Documentation
site_description: Uma API REST completa para gerenciamento de carros.
site_author: L.Phillipe

theme:
  name: material
  font:
    text: Roboto

plugins:
  - search

nav:
  - Início: index.md
  - Pré-requisitos: prerequisites.md
  - Instalação: installation.md
  - Configuração: configuration.md
  - Guidelines e padrões: guidelines.md
  - Estrutura: structure.md
  - API Endpoints: api_endpoints.md
  - Modelagem do Sistema: system_modeling.md
  - Autenticação e segurança: authentication_security.md
  - Desenvolvimento: development.md
  - Testes: tests.md
  - Deploy: deploy.md
  - Contribuição: contribution.md
  - Release Notes: release_notes.md


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
