---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-api-mkdocs
  namespace: fastapi-car-api
  labels:
    app: car-api-mkdocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-api-mkdocs
  template:
    metadata:
      labels:
        app: car-api-mkdocs
    spec:
      containers:
      - name: car-api-mkdocs
        image: car-api-mkdocs:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: car-api-mkdocs
  namespace: fastapi-car-api
spec:
  selector:
    app: car-api-mkdocs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-api-mkdocs-ingress
  namespace: fastapi-car-api
spec:
  ingressClassName: kong
  rules:
  - host: car-api-mkdocs.localhost.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:  
          service:
            name: car-api-mkdocs
            port:
              number: 80


