---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: registry.k8s.io/busybox
      command:
        - ls
        - "-l"
        - "/etc/secret-volume"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-api
  namespace: fastapi-car-api
  labels:
    app: car-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-api
  template:
    metadata:
      labels:
        app: car-api
    spec:
      containers:
      - name: car-api
        image: car-api:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: car-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: car-api
  namespace: fastapi-car-api
spec:
  selector:
    app: car-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-api-ingress
  namespace: fastapi-car-api
spec:
  ingressClassName: kong
  rules:
  - host: car-api.localhost.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:  
          service:
            name: car-api
            port:
              number: 8000


