---
apiVersion: v1
kind: Secret
metadata:
  name: car-api-secret
  namespace: fastapi-car-api
stringData:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/postgres
  JWT_SECRET_KEY: w9AVdI1b7FD5h9bzD9Ato4P6jTKo7AAz9EwxCcKGg9sJCk7dauwkIJAA4Gw4sTji